export const products = [
    {
        name: 'Top Iris Estampa Baby',
        price: 2900,
        stock: 10,
        img: 'https://res.cloudinary.com/peuquedev/image/upload/v1637607748/Alima/top_iris_estampa_baby_dmjoaa.jpg',
        categoryId: 'tops',
        cartCount: 0,
    },
    {
        name: 'Top Lily Estampa Amatista',
        price: 2900,
        stock: 10,
        img: 'https://res.cloudinary.com/peuquedev/image/upload/v1637607765/Alima/top_lily_estampa_amatista_xmgdlh.jpg',
        categoryId: 'tops',
        cartCount: 0,
    },
    {
        name: 'Top Iris Flower Power',
        price: 2900,
        stock: 10,
        img: 'https://res.cloudinary.com/peuquedev/image/upload/v1637607758/Alima/top_iris_estampa_flower_power_gvkzow.jpg',
        categoryId: 'tops',
        cartCount: 0,
    },
    {
        name: 'Biker Estampa Baby',
        price: 2900,
        stock: 10,
        img: 'https://res.cloudinary.com/peuquedev/image/upload/v1637607711/Alima/biker_estampa_baby_vk9kax.jpg',
        categoryId: 'bikers',
        cartCount: 0,
    },
    {
        name: 'Biker Estampa Flower Power',
        price: 2900,
        stock: 10,
        img: 'https://res.cloudinary.com/peuquedev/image/upload/v1637607720/Alima/biker_estampa_flower_power_f73chp.jpg',
        categoryId: 'bikers',
        cartCount: 0,
    },
    {
        name: 'Biker Estampa Mudras',
        price: 2900,
        stock: 10,
        img: 'https://res.cloudinary.com/peuquedev/image/upload/v1637607734/Alima/biker_estampa_mudras_zvpqpi.jpg',
        categoryId: 'bikers',
        cartCount: 0,
    },
    {
        name: 'Biker Estampa Psicodélica',
        price: 2900,
        stock: 10,
        img: 'https://res.cloudinary.com/peuquedev/image/upload/v1637607741/Alima/biker_estampa_psicodelica_heqmn2.jpg',
        categoryId: 'bikers',
        cartCount: 0,
    },
];
